### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [lhs4297/PY202309#2]
### 없는 파일
- challenge/week6/function.ipynb
- practice/week6/function.ipynb
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

#### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week3/dict_and_set
    - 44:Undefined variable 'avg_scores'	for movie, avg_score in avg_scores.items():
        - avg_scores 변수가 없습니다.  초기화 후 사용하세요.
- WARNING in challenge/week3/list_and_tuple
    - 46:Undefined variable 'selected_sports'	print( selected_sports, "has index number : ", len(select_sports))   # output the length of the index received by input
         - selected_sports 변수가 없습니다. 변수 이름을 체크해주세요.

- WARNING in challenge/week7/todo_extend
    - 18:Undefined variable 'i'	        task = task_list[i]
    - 19:Undefined variable 'i'	        print(f"{i+1}. {task}")
    - 17:Unused variable 'I'	    for I in range(len(task_list)):
         - for 문에서는 I (대문자 i)에 숫자를 넣어주고 있으나, 리스트 접근 시 소문자 i로 접근하고 있습니다. 모두 소문자로 통일해주세요. 
         
- WARNING in practice/week3/turtle
    - 31:Bad indentation. Found 8 spaces, expected 4	        print("turtle bye!")
         - 들여쓰기를 맞춰주세요. 
         

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week3/list_and_tuple
- Insufficient comments in project/week8/search_engine

**Comment by lhs4297** [comment]
해결했습니다.
